---
deployment:
  tasks:
    - export DEPLOYPATH=/home/hj3f8m4zmdju/repositories/mrserviceexpertnextjs
    - cd $DEPLOYPATH && source /home/hj3f8m4zmdju/nodevenv/repositories/mrserviceexpertnextjs/24/bin/activate && npm install --include=dev && npm run build
    - mkdir -p $DEPLOYPATH/tmp
    - touch $DEPLOYPATH/tmp/restart.txt