version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/mrserviceexpertnextjs

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 600
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
